name: Pull Variables from Environment
on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source Repo (OWNER/REPO)'
        required: true
      source_env:
        description: 'Select Environment to pull from'
        required: true
        type: choice
        options: [dev, test, prod]
      output_json_path:
        description: 'Path to save JSON file'
        required: true
        default: 'pulled_vars.json'
permissions:
  contents: write
  pull-requests: write

jobs:
  pull-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Fetch and Format Variables
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          REPO="${{ github.event.inputs.source_repo }}"
          ENV="${{ github.event.inputs.source_env }}"
          FILE="${{ github.event.inputs.output_json_path }}"
          
          # Move the pipe to the end of the line for better reliability
          gh variable list --repo "$REPO" --env "$ENV" --json name,value | \
          jq 'reduce .[] as $item ({}; .[$item.name] = $item.value)' > "$FILE"

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "feat(extract): update artifacts"
          branch: feat/extract-${{ github.run_number }}
          title: "feat(extract): update artifacts"
          body: "This PR contains the extracted variables from ${{ github.event.inputs.source_repo }} for the ${{ github.event.inputs.source_env }} environment."
          add-paths: |
            ${{ github.event.inputs.output_json_path }}
